apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: run-precompute-data-embedding
spec:
  serviceAccountName: workflow
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 64Gi
  entrypoint: main
  arguments:
    parameters:
      - name: params-conf-list
        value: '[
          {"NAF": "naf_rev2", "METHODS": "regex fuzzy similarity"},
          {"NAF": "naf_2025", "METHODS": "regex fuzzy similarity"},
          ]'

  templates:
    - name: main
      dag:
        tasks:
          - name: precompute-sentence-embedding
            template: run-precompute-embedding
            arguments:
              parameters:
                - name: NAF
                  value: "{{item.NAF}}"
                - name: METHODS
                  value: "{{item.METHODS}}"
            withParam: "{{workflow.parameters.params-conf-list}}"
    - name: run-cleansing
      inputs:
        parameters:
          - name: NAF
          - name: METHODS
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nvidia.com/gpu.product
                    operator: In
                    values:
                      - NVIDIA-H100-NVL
                      - NVIDIA-H100-PCIe
      container:
        image: inseefrlab/onyxia-vscode-pytorch:py3.12.11-gpu
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            nvidia.com/gpu: 1
        command: ["/bin/bash", -c]
        args:
          - |
            git clone https://github.com/InseeFrLab/codif-ape-preprocess.git
            cd codif-ape-preprocess/
            uv sync
            uv run python -m src.label_cleaning.tools.load_vector_db
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        env:
          # env var for s3 connexion
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: my-s3-creds
                key: accessKey
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: my-s3-creds
                key: secretKey
          - name: AWS_DEFAULT_REGION
            value: us-east-1
          - name: AWS_S3_ENDPOINT
            value: minio.lab.sspcloud.fr